// Staff-only test personas (gated by profiles.is_staff). Each one exists to exercise a specific
// branch of the catalog — the "Tests:" line in its description says exactly which. Keep these in
// sync with SLOTS: `npm run audit` fails if a persona answers a field the interview doesn't ask,
// and smoke-builds every persona's plan.

export type Persona = {
  name: string;
  description: string;
  answers: Record<string, unknown>;
};

export const TEST_PERSONAS: Persona[] = [
  {
    name: 'Andrew — US family, dual-ES household',
    description: 'US nationals, remote worker, wife holds an ES passport (household is EU → eu_citizen path). Tests: EU fast-path, family cluster, driving, Modelo 720 assets.',
    answers: {
      speaks_spanish:                       'A little',
      nationalities:                        ['US', 'ES'],
      work_situation:                       'employed_remote',
      employer_country_is_foreign:          true,
      has_spouse_or_partner:                true,
      partner_is_married:                   true,
      has_children:                         true,
      intends_long_stay:                    true,
      arrival_date:                         '2026-09-01',
      has_spanish_address:                  true,
      owns_or_drives:                       true,
      owns_property_in_spain:               false,
      region:                               'madrid',
      has_pets:                             false,
      foreign_assets_eur_band:              'over €700k',
    },
  },
  {
    name: 'Susan — US retiree, NLV, aiming for citizenship',
    description: 'US passive income, married, no address yet, still choosing a region. Tests: NLV document cluster, consulate banner (US), scouting step (undecided where), FULL citizenship track incl. DELE + CCSE (wants citizenship, not Spanish-speaking).',
    answers: {
      speaks_spanish:                       'None yet',
      nationalities:                        ['US'],
      work_situation:                       'passive_income',
      annual_income_eur_band:               '€34k–€60k',
      has_spouse_or_partner:                true,
      partner_is_married:                   true,
      has_children:                         false,
      intends_long_stay:                    true,
      arrival_date:                         '2026-10-15',
      has_spanish_address:                  false,
      owns_or_drives:                       true,
      owns_property_in_spain:               false,
      region:                               'not_sure',
      has_pets:                             false,
      foreign_assets_eur_band:              '€50k–€200k',
      previously_ex_spanish_colony_nationality: false,
      wants_citizenship:                    true,
    },
  },
  {
    name: 'James — UK retiree, renewal-only',
    description: 'British, retired, long stay but plans to keep renewing residence — no citizenship. Tests: rolling-renewal path — nlv-renewal + permanent-residence present, ZERO citizenship items (no DELE / CCSE / application / jura).',
    answers: {
      speaks_spanish:                       'A little',
      nationalities:                        ['GB'],
      work_situation:                       'retired',
      annual_income_eur_band:               '€34k–€60k',
      has_spouse_or_partner:                true,
      partner_is_married:                   true,
      has_children:                         false,
      intends_long_stay:                    true,
      arrival_date:                         '2027-01-10',
      has_spanish_address:                  false,
      owns_or_drives:                       true,
      owns_property_in_spain:               false,
      region:                               'andalucia',
      has_pets:                             false,
      foreign_assets_eur_band:              '€50k–€200k',
      previously_ex_spanish_colony_nationality: false,
      wants_citizenship:                    false,
    },
  },
  {
    name: 'Sofia — Colombian family, 2-year track, DELE-exempt',
    description: 'Colombian (ex-colony AND Spanish-speaking), wants citizenship. Tests: 2-year latam track, CCSE required, DELE correctly ABSENT (Spanish-speaking exemption), school enrollment.',
    answers: {
      speaks_spanish:                       'Fluent or native',
      nationalities:                        ['CO'],
      work_situation:                       'passive_income',
      annual_income_eur_band:               '€28k–€34k',
      has_spouse_or_partner:                true,
      partner_is_married:                   true,
      has_children:                         true,
      intends_long_stay:                    true,
      arrival_date:                         '2026-11-01',
      has_spanish_address:                  true,
      owns_or_drives:                       true,
      owns_property_in_spain:               false,
      region:                               'comunidad-valenciana',
      has_pets:                             false,
      foreign_assets_eur_band:              'under €50k',
      previously_ex_spanish_colony_nationality: true,
      wants_citizenship:                    true,
    },
  },
  {
    name: 'Paolo — Filipino remote worker, DNV',
    description: 'Filipino working remotely for a foreign employer (DNV path), wants citizenship. Ex-colony but NOT Spanish-speaking. Tests: the DELE fix — 2-year latam track present AND DELE A2 still REQUIRED (PH is not exempt), CCSE required, DNV document cluster.',
    answers: {
      speaks_spanish:                       'Conversational',
      nationalities:                        ['PH'],
      work_situation:                       'employed_remote',
      employer_country_is_foreign:          true,
      annual_income_eur_band:               '€34k–€60k',
      has_spouse_or_partner:                false,
      has_children:                         false,
      intends_long_stay:                    true,
      arrival_date:                         '2026-12-01',
      has_spanish_address:                  true,
      owns_or_drives:                       false,
      owns_property_in_spain:               false,
      region:                               'cataluna',
      has_pets:                             false,
      foreign_assets_eur_band:              'under €50k',
      previously_ex_spanish_colony_nationality: true,
      wants_citizenship:                    true,
    },
  },
  {
    name: 'Elena — Canadian with unmarried partner',
    description: 'Canadian NLV mover whose partner is not married/registered. Tests: family-reunification correctly ABSENT (requires marriage or registered partnership); partner still raises the NLV income threshold.',
    answers: {
      speaks_spanish:                       'A little',
      nationalities:                        ['CA'],
      work_situation:                       'passive_income',
      annual_income_eur_band:               '€34k–€60k',
      has_spouse_or_partner:                true,
      partner_is_married:                   false,
      has_children:                         false,
      intends_long_stay:                    true,
      arrival_date:                         '2027-02-01',
      has_spanish_address:                  true,
      owns_or_drives:                       false,
      owns_property_in_spain:               false,
      region:                               'galicia',
      has_pets:                             false,
      foreign_assets_eur_band:              '€50k–€200k',
      previously_ex_spanish_colony_nationality: false,
      wants_citizenship:                    true,
    },
  },
  {
    name: 'Kenji — Japanese freelancer, property buyer',
    description: 'Japanese contractor (DNV), buying property, has a dog, renewal-only. Tests: autónomo/tax cluster, full property cluster (due diligence, notary, registry, ITP, IBI, comunidad — anchored to the purchase date), pet import, DGT exchange (JP has a bilateral agreement), no citizenship items.',
    answers: {
      speaks_spanish:                       'None yet',
      nationalities:                        ['JP'],
      work_situation:                       'contractor_freelance',
      annual_income_eur_band:               '€60k+',
      has_spouse_or_partner:                false,
      has_children:                         false,
      intends_long_stay:                    true,
      arrival_date:                         '2027-03-01',
      has_spanish_address:                  true,
      owns_or_drives:                       true,
      owns_property_in_spain:               true,
      property_purchase:                    '2027-04-15',
      region:                               'madrid',
      has_pets:                             true,
      foreign_assets_eur_band:              '€200k–€700k',
      previously_ex_spanish_colony_nationality: false,
      wants_citizenship:                    false,
    },
  },
  {
    name: 'Mara — German remote worker, short stay',
    description: 'EU national, under 183 days. Tests: EU path with a slim plan — no visa docs, no tax-residency items; citizenship question never asked (EU).',
    answers: {
      speaks_spanish:                       'Conversational',
      nationalities:                        ['DE'],
      work_situation:                       'employed_remote',
      employer_country_is_foreign:          true,
      has_spouse_or_partner:                false,
      has_children:                         false,
      intends_long_stay:                    false,
      arrival_date:                         '2026-08-15',
      has_spanish_address:                  true,
      owns_or_drives:                       false,
      owns_property_in_spain:               false,
      region:                               'baleares',
      has_pets:                             false,
    },
  },
  {
    name: 'Minimal — EU, fewest obligations',
    description: 'French national, short stay, rented flat, nothing extra. Tests: the floor — the smallest non-empty plan (padrón + health card) still renders and phases correctly. (NB: with no address at all the plan is EMPTY today — the catalog has no EU-registration item yet; flagged for the sourcing pass.)',
    answers: {
      speaks_spanish:                       'Conversational',
      nationalities:                        ['FR'],
      work_situation:                       'employed_remote',
      employer_country_is_foreign:          true,
      has_spouse_or_partner:                false,
      has_children:                         false,
      intends_long_stay:                    false,
      has_spanish_address:                  true,
      owns_or_drives:                       false,
      owns_property_in_spain:               false,
      region:                               'pais-vasco',
      has_pets:                             false,
    },
  },
];
