import Head from '@/components/SeoHead';
import { usePathname } from 'expo-router';
import { WEB_LOCALES } from '@/lib/i18n';

// One component = the full search + social tag set, so no page can ship half of it.
// Links to Get Camino live or die in WhatsApp threads and expat Facebook groups — the share
// card (public/og-card.png, generated by scripts/gen-share-card.mjs) is what they unfurl to.
// Head is the platform-split SeoHead: web renders real tags, native renders nothing.
//
// L2: pages that exist per locale pass `localized` — Seo then (a) points the canonical at the
// CURRENT route's variant (/es/… pages canonicalize to themselves, never to English), and
// (b) lists hreflang alternates for every shipped web locale plus x-default = English.
// JSON-LD gains inLanguage matching the variant.

const DEFAULT_IMAGE = 'https://getcamino.app/og-card.png';

export default function Seo({ title, description, canonical, image = DEFAULT_IMAGE, jsonLd, localized, noindex }: {
  title: string; description: string; canonical: string; image?: string;
  // schema.org structured data (an object or several) — rendered as application/ld+json.
  jsonLd?: object | object[];
  // This page has /<locale>/ variants (the [locale] tree re-exports it).
  localized?: boolean;
  // Personal/ephemeral content (e.g. /shared roadmaps) — keep out of search indexes.
  noindex?: boolean;
}) {
  const pathname = usePathname();
  const seg = pathname?.split('/')[1];
  const routeLocale = localized && seg && (WEB_LOCALES as string[]).includes(seg) ? seg : null;

  // `canonical` is always passed as the English URL; derive the variant URLs from it.
  const enUrl = canonical;
  const urlFor = (locale: string) => {
    const u = new URL(enUrl);
    u.pathname = `/${locale}${u.pathname === '/' ? '' : u.pathname}`;
    return u.toString();
  };
  const selfUrl = routeLocale ? urlFor(routeLocale) : enUrl;

  const withLanguage = (obj: object): object =>
    ({ inLanguage: routeLocale ?? 'en', ...obj });
  const jsonLdOut = jsonLd
    ? (Array.isArray(jsonLd) ? jsonLd.map(withLanguage) : withLanguage(jsonLd))
    : undefined;

  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={description} />
      {noindex && <meta name="robots" content="noindex" />}
      <link rel="canonical" href={selfUrl} />
      {localized && <link rel="alternate" hrefLang="en" href={enUrl} />}
      {localized && WEB_LOCALES.map(l => (
        <link key={l} rel="alternate" hrefLang={l} href={urlFor(l)} />
      ))}
      {localized && <link rel="alternate" hrefLang="x-default" href={enUrl} />}
      <meta property="og:type" content="website" />
      <meta property="og:site_name" content="Get Camino" />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={selfUrl} />
      <meta property="og:image" content={image} />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={image} />
      {jsonLdOut && (
        <script type="application/ld+json">
          {JSON.stringify(Array.isArray(jsonLdOut) && jsonLdOut.length === 1 ? jsonLdOut[0] : jsonLdOut)}
        </script>
      )}
    </Head>
  );
}
