import Head from '@/components/SeoHead';

// One component = the full search + social tag set, so no page can ship half of it.
// Links to Camino live or die in WhatsApp threads and expat Facebook groups — the share
// card (public/og-card.png, generated by scripts/gen-share-card.mjs) is what they unfurl to.
// Head is the platform-split SeoHead: web renders real tags, native renders nothing.

const DEFAULT_IMAGE = 'https://getcamino.app/og-card.png';

export default function Seo({ title, description, canonical, image = DEFAULT_IMAGE, jsonLd }: {
  title: string; description: string; canonical: string; image?: string;
  // schema.org structured data (an object or several) — rendered as application/ld+json.
  jsonLd?: object | object[];
}) {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={description} />
      <link rel="canonical" href={canonical} />
      <meta property="og:type" content="website" />
      <meta property="og:site_name" content="Camino" />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={canonical} />
      <meta property="og:image" content={image} />
      <meta property="og:image:width" content="1200" />
      <meta property="og:image:height" content="630" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={image} />
      {jsonLd && (
        <script type="application/ld+json">
          {JSON.stringify(Array.isArray(jsonLd) && jsonLd.length === 1 ? jsonLd[0] : jsonLd)}
        </script>
      )}
    </Head>
  );
}
